const questionsToAsk = [
    {
        legend : "-Quel est le nom de la créature magique que seuls ceux qui ont vu la mort peuvent voir ?-",
        R1 : "Un hippogriffe",
        R2 : "Un thestral",
        R3 : "Un traquenard",
        R4 : "Un niffleur",
        lienValider : "#R2",
    },
    {
        legend : "-Quel est le prénom de Voldemort ?-",
        R1 : "Tom",
        R2 : "Albus",
        R3 : "Severus",
        R4 : "Jean-Yves",
        lienValider : "#R1",
    },
    {
        legend : "-Quel est le nom du professeur de potions à Poudlard dans les premiers livres ?-",
        R1 : "Horace Slughorn",
        R2 : "Severus Rogue",
        R3 : "Snoop Dogg",
        R4 : "Gilderoy Lockhart",
        lienValider : "#R2",
    },
    {
        legend : "-Quel est le nom du serpent de Voldemort ?-",
        R1 : "Basilic",
        R2 : "Nagini",
        R3 : "Fumseck",
        R4 : "Maurice",
        lienValider : "#R2",
    },
    {
        legend : "-Quelle position Harry joue-t-il dans l'équipe de Quidditch de Gryffondor ?-",
        R1 : "Défenseur central",
        R2 : "Gardien",
        R3 : "Batteur",
        R4 : "Attrapeur",
        lienValider : "#R4",
    },
    {
        legend : "-Quel est le nom du pub où Harry rencontre Hagrid pour la première fois ?-",
        R1 : "Le Chaudron Baveur",
        R2 : "Le Poudlard Express",
        R3 : "La Taverne des Trois Balais",
        R4 : "Le balai dans les fesses",
        lienValider : "#R1",
    },
    {
        legend : "-Qui a tué Dobby, l'elfe de maison ?-",
        R1 : "Lucius Malfoy",
        R2 : "La drogue",
        R3 : "Bellatrix Lestrange",
        R4 : "Fenrir Greyback",
        lienValider : "#R3",
    },
    {
        legend : "-Quel sort Harry utilise-t-il pour désarmer ses adversaires ?-",
        R1 : "Expelliarmus",
        R2 : "Stupefix",
        R3 : "Déshabillus",
        R4 : "Avada Kedavra",
        lienValider : "#R1",
    },
    {
        legend : "-Quelle est la couleur des Beuglantes (les lettres magiques qui crient)?-",
        R1 : "Jaune",
        R2 : "Rouge",
        R3 : "Blanche",
        R4 : "Indigo du web",
        lienValider : "#R2",
    },
    {
        legend : "-Quel est le nom du dragon que Hagrid élève dans 'Harry Potter et la Coupe de Feu' ?-",
        R1 : "Norbert",
        R2 : "Jean",
        R3 : "Smaug",
        R4 : "Fumseck",
        lienValider : "#R1",
    },
];

export default questionsToAsk;